name: "Desktop Build"

on:
  push:
    branches:
      - master
    paths:
      - "client/desktop/**"
  workflow_dispatch:

jobs:
  build-desktop:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-latest
          # - ubuntu-latest
          - windows-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install global dependencies
        uses: pnpm/action-setup@v2.0.1
        with:
          version: latest
          run_install: true

      - name: Install npm dependencies
        run: yarn
        working-directory: ./client/desktop

      - name: Build/release Electron app
        uses: paneron/action-electron-builder@v1.8.1
        with:
          package_root: ./client/desktop

          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.github_token }}

          release: false
          # # If the commit is tagged with a version (e.g. "v1.0.0"),
          # # release the app after building
          # release: ${{ startsWith(github.ref, 'refs/tags/v') }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: desktop-client-artifacts
          path: ./client/desktop/release/build
